site_name: app
site_description: Its all about a Weissman score > 5.0
repo_url: https://github.com/psdon/app
site_dir: site
copyright: Copyright &copy; 2020, <a href="https://github.com/psdon">psdon</a>.
dev_addr: 0.0.0.0:8001

nav:
  - Home: 'index.md'
  - API:
    - To Do: 'api/todo.md'
