# Generated by Django 3.1 on 2020-08-26 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_added', models.DateTimeField(auto_created=True)),
                ('name', models.CharField(max_length=255)),
                ('todo_status', models.CharField(choices=[('c', 'completed'), ('nc', 'not_completed')], max_length=2)),
                ('active_status', models.BooleanField(default=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('user_uuid', models.UUIDField()),
            ],
        ),
    ]
