# Generated by Django 3.1 on 2020-08-26 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20200826_0717'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='user_uuid',
            new_name='user_id',
        ),
        migrations.AlterField(
            model_name='todo',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='todo',
            name='todo_status',
            field=models.CharField(choices=[('nc', 'not_completed'), ('c', 'completed')], max_length=2),
        ),
    ]
